-- 수정 전 스키마(V1 inventory_tx: created_at 기본값 now(), V21 stock_balance). 필요한 열만 둔다.
drop table if exists inventory_tx, stock_balance;
create table inventory_tx (
    id         bigint generated by default as identity primary key,
    product_id bigint      not null,
    tx_type    varchar(20) not null,
    qty_delta  int         not null,
    created_at timestamp   not null default now()
);
create table stock_balance (
    product_id  bigint    primary key,
    qty         int       not null,
    last_tx_id  bigint    not null,
    computed_at timestamp not null default now()
);
-- 기존 원장 3행: 입고 +100, 조정 -1, -6. 스냅샷은 V21 백필과 같은 방식(원장 합, MAX(id))으로 만든다.
insert into inventory_tx(product_id, tx_type, qty_delta) values (1,'INBOUND',100),(1,'ADJUST',-1),(1,'ADJUST',-6);
insert into stock_balance (product_id, qty, last_tx_id)
select 1, coalesce(sum(qty_delta),0), coalesce(max(id),0) from inventory_tx where product_id = 1;
select * from stock_balance;
select id, tx_type, qty_delta from inventory_tx order by id;
