CREATE TABLE product (id bigint PRIMARY KEY);
CREATE TABLE inventory_tx (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id bigint NOT NULL REFERENCES product(id), tx_type varchar(20) NOT NULL, qty_delta int NOT NULL, ref_type varchar(50), ref_id bigint, created_at timestamp NOT NULL DEFAULT clock_timestamp(), idempotency_key varchar(80), reason varchar(200));
CREATE INDEX ix_inventory_tx_product_id ON inventory_tx (product_id, id);
CREATE UNIQUE INDEX ux_inventory_tx_idem ON inventory_tx (idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE TABLE stock_balance (product_id bigint PRIMARY KEY REFERENCES product(id), qty int NOT NULL, last_tx_id bigint NOT NULL, computed_at timestamp NOT NULL DEFAULT now());
CREATE VIEW v_stock_on_hand AS SELECT b.product_id, b.qty + COALESCE((SELECT SUM(t.qty_delta) FROM inventory_tx t WHERE t.product_id = b.product_id AND t.id > b.last_tx_id), 0) AS on_hand_qty, b.last_tx_id, b.computed_at FROM stock_balance b;
INSERT INTO product SELECT generate_series(1,17);
